### ISSUE TITLE
Implement i18n Library for Centralized Use

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#134]
To enhance the internationalization (i18n) capabilities of our Digital Experience Platform (DXP) components, we propose the implementation of an i18n library that can be centrally used across all components. This feature is crucial to ensure that our DXP can effectively support multiple languages and regions, providing a localized experience to users around the world.

**Comment by sanskar345** [comment]
**- Unable to access the app files in the pulgin:** 

I tried accessing the app files in the plugin but only able to access the node-modules folder files. 

How i tried to accessing it - by requiring all the files using require.context and giving the path of the apps location.

_Tried to find different ways how it can be done but found nothing._

**- Shifted i18n logic to dxp-components in index.ts. This is because:** 
When taking localeMessages from the app as plugin options and when passing it in context to another location (lets say i18n.ts) and importing the context in the file error occurs of contex.localeMessages used before initialization this is beacause when importing this file from the index.ts the file (i18n.ts) runs first and then the rest logic (of creating the context and assigning localeMessages) in index.ts.

**- Removed the function (to load localeMessages from the locales folder and creating an object):** 

```
function loadLocaleMessages(): LocaleMessages<VueMessageType> {
  const locales = require.context('./locales', true, /[A-Za-z0-9-_,\s]+\.json$/i)
  const messages: LocaleMessages<VueMessageType> = {}
  locales.keys().forEach(key => {
    const matched = key.match(/([A-Za-z0-9-_]+)\./i)
    if (matched && matched.length > 1) {
      const locale = matched[1]
      messages[locale] = locales(key)
    }
  })
  return messages
}
```

The above function just creates an object of JSONs present in the locales file like - { en: { }, es: {} }

Now with the new approach i am just exporting this JSONs from locales folder by creating index.ts and exporting the required object { en: { } } by importing the JSONs in the index.ts

Now importing this object (exported from the locales/index.ts) and passing it dxp options.

_Note - for importing JSONs in typescript added "resolveJsonModule": true configuration in ts config._

**- How process and require can be used in the ts files of dxp:** 

by declaring them like :-
 
`declare var process: any; `
in the file

Here we are telling the TypeScript compiler that there is already a variable named process with the type any. This is useful when you have variables introduced by sources that the compiler is not be aware of.
