### ISSUE TITLE
Implement Centralized Product Scanner 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/dxp-components#137]
This feature aims to provide users with a consistent and reliable tool for scanning product codes across various parts of the application, facilitating tasks such as inventory management, product lookup, and data entry. We will Develop a centralized Product Scanner component that can be seamlessly integrated into different DXP components. This component should be designed to work cohesively with various DXP elements.

**Comment by dt2patel** [comment]
We are focusing on product but this will scan any barcode right? What is the major value prop of this over the direct plug-in we use? @ravilodhi

**Comment by ravilodhi** [comment]
The main idea behind moving the scanner component to dxp-components is its reusability, currently, it is used in receiving, inventory count, and picking apps. Initially, I thought we were using this to scan location, etc., as well, but that is not the case. We can rename this to ProductScanner instead of Scanner to be more specific.
@dt2patel

**Comment by dt2patel** [comment]
I guess my question is still what part of the usability are we aiming to improve with this? Like the modal UI will be handled? can you share details about that? @ravilodhi

**Comment by ravilodhi** [comment]
The scanning part and decoding parts will be reused with this. So on button click modal will be created by the app, with this Scanner component. @dt2patel
