### ISSUE TITLE
Service worker not working in firefox private mode

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/dxp-components#241]

**Comment by amansinghbais** [comment]
As per the findings, In Firefox, Service Worker APIs are hidden and cannot be used when the user is in private browsing mode, or when history is disabled, or if cookies are cleared when Firefox is closed. These APIs are disabled because of security reasons for avoiding Man in middle attack.

Links to findings for this issue: 
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
https://bugzilla.mozilla.org/show_bug.cgi?id=1320796
https://bugzilla.mozilla.org/show_bug.cgi?id=1601916

**Comment by Dhiraj1405** [comment]
Will recreate when needed. Closing
